fix(args): check if required args like src, dest are provided
bharathnayak03/svg-wc-icons pull request #6
Opened 2019-11-06 19:46 UTC by itaditya

fix #5

2019-11-06 19:48 UTC, itaditya commented
Here's how it would look

<img width="842" alt="image" src="https://user-images.githubusercontent.com/15871340/68332282-8026b380-00fc-11ea-85ce-4fd0d03a60aa.png">

2019-11-10 04:56 UTC, bharathnayak03 requested changes

2019-11-10 04:56 UTC, bharathnayak03 commented on src/cli.js
> +    if (!src) {
we can do it using, yargs itself

2019-11-10 05:24 UTC, bharathnayak03 commented
closing this . as the change was done using yargs options

2019-11-10 05:24 UTC, closed without merging

2019-11-10 05:39 UTC, itaditya commented on src/cli.js
> +    if (!src) {
great!